---
- name: Install of confSeeker
  hosts: confseekertarget
  become: true
  gather_facts: false
  roles:
    - installConfSeeker
  tasks:
    - name: "add path to every .bashrc"
      confseeker:
        homeDirectory: "/home"
        shellConf: ".bashrc"

    - name: "adding path for sudoers"
      lineinfile:
        path: /etc/sudoers
        regexp: 'secure_path'
        insertafter: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin'
        line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/opt/addSofts/confSeeker'
